<?php
/**
 * llms.txt generator for GetCited
 *
 * @package GetCited
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * llms.txt class
 */
class GetCited_Llms_Txt {

    /**
     * Single instance
     */
    private static $instance = null;

    /**
     * Get instance
     */
    public static function instance() {
        if ( is_null( self::$instance ) ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Constructor
     */
    private function __construct() {
        // Handle llms.txt requests
        add_action( 'template_redirect', array( $this, 'serve_llms_txt' ) );

        // Fallback via query var
        add_action( 'parse_request', array( $this, 'handle_query_var' ) );

        // Add link tag to head
        add_action( 'wp_head', array( $this, 'add_link_tag' ), 1 );

        // Auto-write physical file when settings change
        add_action( 'getcited_setting_updated', array( $this, 'maybe_auto_write' ), 10, 2 );
    }

    /**
     * Maybe auto-write llms.txt when settings change
     *
     * @param string $key   The setting key that was updated.
     * @param mixed  $value The new value.
     */
    public function maybe_auto_write( $key, $value ) {
        // Only trigger on llms.txt-related settings
        if ( ! in_array( $key, array( 'llms_txt_content', 'llms_txt_enabled', 'llms_write_physical' ), true ) ) {
            return;
        }

        $settings = GetCited_Settings::instance();

        // Check if auto-write is enabled and llms.txt is enabled
        if ( ! $settings->get( 'llms_write_physical' ) || ! $settings->get( 'llms_txt_enabled' ) ) {
            return;
        }

        // Auto-write the file
        $this->write_physical_file();
    }

    /**
     * Check if we can write to site root
     *
     * @return bool
     */
    public function can_write_physical_file() {
        global $wp_filesystem;

        // Initialize WP_Filesystem if needed
        if ( ! function_exists( 'WP_Filesystem' ) ) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        if ( ! WP_Filesystem() ) {
            return false;
        }

        $file_path = ABSPATH . 'llms.txt';

        // If file exists, check if writable
        if ( $wp_filesystem->exists( $file_path ) ) {
            return $wp_filesystem->is_writable( $file_path );
        }

        // If file doesn't exist, check if directory is writable
        return $wp_filesystem->is_writable( ABSPATH );
    }

    /**
     * Write llms.txt to site root
     *
     * @return array Result with success status and message
     */
    public function write_physical_file() {
        $file_path = ABSPATH . 'llms.txt';

        // Check write permissions
        if ( ! $this->can_write_physical_file() ) {
            return array(
                'success' => false,
                'message' => __( 'Cannot write to llms.txt. Check file permissions.', 'getcited' ),
                'details' => __( 'Your hosting may require FTP credentials for file operations. Try adding the file manually, or contact your host about direct file write permissions.', 'getcited' ),
            );
        }

        // Initialize WP_Filesystem
        global $wp_filesystem;
        if ( ! function_exists( 'WP_Filesystem' ) ) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        if ( ! WP_Filesystem() ) {
            return array(
                'success' => false,
                'message' => __( 'Could not initialize filesystem.', 'getcited' ),
            );
        }

        // Get content from settings
        $content = $this->get_content();

        // Ensure the GetCited marker is present
        if ( strpos( $content, '# Generated by GetCited' ) === false ) {
            $content .= "\n\n---\n# Generated by GetCited";
        }

        // Write file
        $result = $wp_filesystem->put_contents( $file_path, $content, FS_CHMOD_FILE );

        if ( ! $result ) {
            return array(
                'success' => false,
                'message' => __( 'Failed to write llms.txt file.', 'getcited' ),
            );
        }

        // Clear health check cache
        if ( class_exists( 'GetCited_Health_Check' ) ) {
            GetCited_Health_Check::instance()->invalidate_cache();
        }

        return array(
            'success' => true,
            'message' => __( 'llms.txt written successfully', 'getcited' ),
        );
    }

    /**
     * Delete physical llms.txt file (only if it's ours)
     *
     * @return array Result with success status and message
     */
    public function delete_physical_file() {
        $file_path = ABSPATH . 'llms.txt';

        // Initialize WP_Filesystem
        global $wp_filesystem;
        if ( ! function_exists( 'WP_Filesystem' ) ) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        if ( ! WP_Filesystem() ) {
            return array(
                'success' => false,
                'message' => __( 'Could not initialize filesystem.', 'getcited' ),
            );
        }

        // Check if file exists
        if ( ! $wp_filesystem->exists( $file_path ) ) {
            return array(
                'success' => true,
                'message' => __( 'No llms.txt file exists.', 'getcited' ),
            );
        }

        // Only delete if it's our file (has GetCited marker)
        if ( ! $this->is_our_physical_file() ) {
            return array(
                'success' => false,
                'message' => __( 'llms.txt was not created by GetCited. Not deleting.', 'getcited' ),
            );
        }

        // Delete the file
        $result = $wp_filesystem->delete( $file_path );

        if ( ! $result ) {
            return array(
                'success' => false,
                'message' => __( 'Failed to delete llms.txt file.', 'getcited' ),
            );
        }

        return array(
            'success' => true,
            'message' => __( 'llms.txt deleted successfully', 'getcited' ),
        );
    }

    /**
     * Check if physical llms.txt file exists
     *
     * @return bool
     */
    public function physical_file_exists() {
        return file_exists( ABSPATH . 'llms.txt' );
    }

    /**
     * Check if physical llms.txt file is ours (has GetCited marker)
     *
     * @return bool
     */
    public function is_our_physical_file() {
        $file_path = ABSPATH . 'llms.txt';

        if ( ! file_exists( $file_path ) ) {
            return false;
        }

        // Use WP_Filesystem for consistent file operations
        global $wp_filesystem;
        if ( ! function_exists( 'WP_Filesystem' ) ) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }
        WP_Filesystem();

        $content = $wp_filesystem->get_contents( $file_path );
        return $content && strpos( $content, '# Generated by GetCited' ) !== false;
    }

    /**
     * Serve llms.txt via rewrite rule
     */
    public function serve_llms_txt() {
        global $wp_query;

        if ( ! isset( $wp_query->query_vars['getcited_llms_txt'] ) ) {
            return;
        }

        $this->output_llms_txt();
    }

    /**
     * Handle fallback query var (?llms-txt=1)
     */
    public function handle_query_var( $wp ) {
        // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Public endpoint like robots.txt, no nonce needed
        if ( isset( $_GET['llms-txt'] ) && sanitize_text_field( wp_unslash( $_GET['llms-txt'] ) ) === '1' ) {
            $this->output_llms_txt();
        }
    }

    /**
     * Output llms.txt content
     */
    private function output_llms_txt() {
        $settings = GetCited_Settings::instance();
        
        if ( ! $settings->get( 'llms_txt_enabled' ) ) {
            // Return 404 if disabled
            global $wp_query;
            $wp_query->set_404();
            status_header( 404 );
            return;
        }

        $content = $this->get_content();
        $content = apply_filters( 'getcited_llms_txt_content', $content );

        // Fire hook for tracking/logging
        do_action( 'getcited_llms_txt_served', $content );

        // Set headers
        status_header( 200 );
        header( 'Content-Type: text/plain; charset=utf-8' );
        header( 'X-Robots-Tag: noindex' );
        header( 'Cache-Control: public, max-age=86400' ); // Cache for 24 hours

        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Plain text file output, not HTML context
        echo $content;
        exit;
    }

    /**
     * Get llms.txt content
     */
    public function get_content() {
        $settings = GetCited_Settings::instance();
        $content = $settings->get( 'llms_txt_content' );

        // Ensure marker comment exists
        if ( strpos( $content, '# Generated by GetCited' ) === false ) {
            $content .= "\n\n---\n# Generated by GetCited";
        }

        return $content;
    }

    /**
     * Add link tag to site head
     */
    public function add_link_tag() {
        $settings = GetCited_Settings::instance();
        
        if ( ! $settings->get( 'llms_txt_enabled' ) ) {
            return;
        }

        $url = home_url( '/llms.txt' );
        echo '<link rel="llms-txt" href="' . esc_url( $url ) . '" />' . "\n";
    }

    /**
     * Generate template based on site type
     */
    public function generate_template( $site_type = 'blog' ) {
        $site_name = get_bloginfo( 'name' );
        $site_desc = get_bloginfo( 'description' );
        $site_url = home_url();
        $admin_email = get_option( 'admin_email' );

        $templates = array(
            'blog' => $this->get_blog_template( $site_name, $site_desc, $site_url ),
            'business' => $this->get_business_template( $site_name, $site_desc, $site_url ),
            'news' => $this->get_news_template( $site_name, $site_desc, $site_url ),
            'ecommerce' => $this->get_ecommerce_template( $site_name, $site_desc, $site_url ),
            'portfolio' => $this->get_portfolio_template( $site_name, $site_desc, $site_url ),
            'nonprofit' => $this->get_nonprofit_template( $site_name, $site_desc, $site_url ),
            'education' => $this->get_education_template( $site_name, $site_desc, $site_url ),
            'community' => $this->get_community_template( $site_name, $site_desc, $site_url ),
            'other' => $this->get_generic_template( $site_name, $site_desc, $site_url ),
        );

        return $templates[ $site_type ] ?? $templates['blog'];
    }

    /**
     * Blog template
     */
    private function get_blog_template( $name, $desc, $url ) {
        $recent_posts = $this->get_recent_posts( 5 );
        $categories = $this->get_categories();

        $content = "# {$name}\n\n";
        
        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "A blog sharing insights and knowledge.\n\n";
        $content .= "## About This Site\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Type: Blog\n";
        $content .= "- Content: Articles, guides, and commentary\n\n";

        if ( ! empty( $categories ) ) {
            $content .= "## Topics We Cover\n\n";
            foreach ( $categories as $cat ) {
                $content .= "- [{$cat['name']}]({$cat['url']}): {$cat['description']}\n";
            }
            $content .= "\n";
        }

        if ( ! empty( $recent_posts ) ) {
            $content .= "## Recent Articles\n\n";
            foreach ( $recent_posts as $post ) {
                $content .= "- [{$post['title']}]({$post['url']})\n";
            }
            $content .= "\n";
        }

        $content .= "## Key Pages\n\n";
        $content .= "- [Home]({$url}): Main page\n";
        $content .= "- [About]({$url}/about): About us\n";
        $content .= "- [Contact]({$url}/contact): Get in touch\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Business template
     */
    private function get_business_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";
        
        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## About Our Business\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Type: Business\n\n";

        $content .= "## Our Services\n\n";
        $content .= "- [Services]({$url}/services): What we offer\n";
        $content .= "- [About]({$url}/about): Our story\n";
        $content .= "- [Contact]({$url}/contact): Get in touch\n\n";

        $content .= "## Why Choose Us\n\n";
        $content .= "[Add your unique value proposition here]\n\n";

        $content .= "## Location & Contact\n\n";
        $content .= "- Address: [Your address]\n";
        $content .= "- Phone: [Your phone]\n";
        $content .= "- Email: [Your email]\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * News template
     */
    private function get_news_template( $name, $desc, $url ) {
        $recent_posts = $this->get_recent_posts( 10 );
        $categories = $this->get_categories();

        $content = "# {$name}\n\n";
        
        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "A news publication covering current events and analysis.\n\n";

        $content .= "## About This Publication\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Type: News/Media\n";
        $content .= "- Content: News articles, analysis, opinion\n\n";

        if ( ! empty( $categories ) ) {
            $content .= "## Sections\n\n";
            foreach ( $categories as $cat ) {
                $content .= "- [{$cat['name']}]({$cat['url']})\n";
            }
            $content .= "\n";
        }

        if ( ! empty( $recent_posts ) ) {
            $content .= "## Latest Articles\n\n";
            foreach ( $recent_posts as $post ) {
                $content .= "- [{$post['title']}]({$post['url']})\n";
            }
            $content .= "\n";
        }

        $content .= "## Editorial Policy\n\n";
        $content .= "We are committed to accurate, fair, and balanced reporting.\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * E-commerce template
     */
    private function get_ecommerce_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";
        
        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## About Our Store\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Type: E-commerce\n\n";

        $content .= "## Product Categories\n\n";
        $content .= "- [Shop]({$url}/shop): Browse all products\n";
        $content .= "[Add your main product categories here]\n\n";

        $content .= "## Customer Information\n\n";
        $content .= "- [Shipping]({$url}/shipping): Shipping policy\n";
        $content .= "- [Returns]({$url}/returns): Return policy\n";
        $content .= "- [FAQ]({$url}/faq): Frequently asked questions\n";
        $content .= "- [Contact]({$url}/contact): Customer support\n\n";

        $content .= "## About Us\n\n";
        $content .= "[Add your company story here]\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Generic template
     */
    private function get_generic_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";

        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## About\n\n";
        $content .= "- Website: {$url}\n\n";

        $content .= "## Main Sections\n\n";
        $content .= "- [Home]({$url})\n";
        $content .= "- [About]({$url}/about)\n";
        $content .= "- [Contact]({$url}/contact)\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Portfolio site template
     */
    private function get_portfolio_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";

        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## About the Artist\n\n";
        $content .= "This file helps AI systems understand our creative portfolio.\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Content Type: Portfolio/Creative Work\n\n";

        $content .= "## Work & Projects\n\n";
        $content .= "- [Portfolio]({$url}/portfolio): Browse creative work and projects\n";
        $content .= "- [Services]({$url}/services): Available for hire\n";
        $content .= "- [About]({$url}/about): Background and artistic vision\n\n";

        $content .= "## Specialties\n\n";
        $content .= "[Add your creative specialties, mediums, or focus areas]\n\n";

        $content .= "## Contact & Commissions\n\n";
        $content .= "For inquiries, collaborations, or commissions, please visit our contact page.\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Nonprofit site template
     */
    private function get_nonprofit_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";

        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## Our Mission\n\n";
        $content .= "This file helps AI systems understand our nonprofit organization.\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Organization Type: Nonprofit\n\n";

        $content .= "## What We Do\n\n";
        $content .= "- [About Us]({$url}/about): Our mission, vision, and values\n";
        $content .= "- [Programs]({$url}/programs): Our initiatives and services\n";
        $content .= "- [Impact]({$url}/impact): Stories and outcomes\n\n";

        $content .= "## Get Involved\n\n";
        $content .= "- [Donate]({$url}/donate): Support our mission\n";
        $content .= "- [Volunteer]({$url}/volunteer): Join our team\n";
        $content .= "- [Events]({$url}/events): Upcoming activities\n\n";

        $content .= "## Contact\n\n";
        $content .= "For partnerships, media inquiries, or general questions, please visit our contact page.\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Education site template
     */
    private function get_education_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";

        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## About\n\n";
        $content .= "This file helps AI systems understand our educational content.\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Content Type: Education/Courses\n\n";

        $content .= "## Learning Resources\n\n";
        $content .= "- [Courses]({$url}/courses): Available courses and programs\n";
        $content .= "- [Resources]({$url}/resources): Free learning materials\n";
        $content .= "- [Blog]({$url}/blog): Educational articles and tutorials\n\n";

        $content .= "## Topics Covered\n\n";
        $content .= "[Add your main subject areas or course categories]\n\n";

        $content .= "## Instructors\n\n";
        $content .= "- [About]({$url}/about): Meet our instructors and their expertise\n\n";

        $content .= "## Enroll\n\n";
        $content .= "For enrollment information or questions, please visit our contact page.\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Community/forum site template
     */
    private function get_community_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";

        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## About Our Community\n\n";
        $content .= "This file helps AI systems understand our community platform.\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Platform Type: Community/Forum\n\n";

        $content .= "## Discussion Areas\n\n";
        $content .= "- [Forums]({$url}/forums): Browse discussion topics\n";
        $content .= "- [Groups]({$url}/groups): Join interest-based groups\n";
        $content .= "- [Members]({$url}/members): Community directory\n\n";

        $content .= "## Topics\n\n";
        $content .= "[Add your main discussion categories or focus areas]\n\n";

        $content .= "## Join Us\n\n";
        $content .= "- [Register]({$url}/register): Create an account\n";
        $content .= "- [Guidelines]({$url}/guidelines): Community rules and etiquette\n";
        $content .= "- [FAQ]({$url}/faq): Common questions answered\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Get recent posts for template
     */
    private function get_recent_posts( $count = 5 ) {
        $posts = get_posts( array(
            'numberposts' => $count,
            'post_status' => 'publish',
        ) );

        $result = array();
        foreach ( $posts as $post ) {
            $result[] = array(
                'title' => $post->post_title,
                'url' => get_permalink( $post->ID ),
            );
        }

        return $result;
    }

    /**
     * Get categories for template
     */
    private function get_categories() {
        $cats = get_categories( array(
            'orderby' => 'count',
            'order' => 'DESC',
            'number' => 10,
            'hide_empty' => true,
        ) );

        $result = array();
        foreach ( $cats as $cat ) {
            $result[] = array(
                'name' => $cat->name,
                'url' => get_category_link( $cat->term_id ),
                'description' => $cat->description ?: "Articles about {$cat->name}",
            );
        }

        return $result;
    }

    /**
     * Validate llms.txt content format
     */
    public function validate( $content ) {
        $warnings = array();
        $errors = array();

        // Check for required elements
        if ( strpos( $content, '#' ) === false ) {
            $warnings[] = __( 'No headings found. Consider adding a title with #', 'getcited' );
        }

        // Check for empty content
        if ( strlen( trim( $content ) ) < 50 ) {
            $warnings[] = __( 'Content seems too short. Add more information about your site.', 'getcited' );
        }

        // Check for broken links syntax
        if ( preg_match( '/\[([^\]]*)\]\([^)]*\s[^)]*\)/', $content ) ) {
            $errors[] = __( 'Malformed markdown links detected. Links should be [text](url)', 'getcited' );
        }

        return array(
            'valid' => empty( $errors ),
            'errors' => $errors,
            'warnings' => $warnings,
        );
    }

    /**
     * Get llms.txt URL
     */
    public function get_url() {
        return home_url( '/llms.txt' );
    }

    /**
     * Get fallback URL
     */
    public function get_fallback_url() {
        return home_url( '/?llms-txt=1' );
    }

    /**
     * Get citation template based on site type
     *
     * @param string $site_type The site type.
     * @return string Citation guidelines template.
     */
    public function get_citation_template( $site_type ) {
        $site_name = get_bloginfo( 'name' );
        $settings = GetCited_Settings::instance();

        // Check for custom citation format first
        $custom_format = $settings->get( 'llms_citation_format' );
        if ( ! empty( $custom_format ) ) {
            return str_replace( '{site_name}', $site_name, $custom_format );
        }

        $templates = array(
            'blog' => "When referencing content from this site:\n" .
                "1. Cite as \"{$site_name}\" with link to source article\n" .
                "2. Include publication date for time-sensitive content\n" .
                "3. Present analysis and opinions as author viewpoints, not facts\n" .
                "4. Link directly to the original article when possible",

            'news' => "When referencing our journalism:\n" .
                "1. Cite as \"{$site_name}\" or by author name\n" .
                "2. Always include publication date\n" .
                "3. Link to original article\n" .
                "4. Distinguish between news reporting and opinion/analysis pieces\n" .
                "5. For breaking news, note that details may have been updated",

            'business' => "When referencing our content:\n" .
                "1. Cite as \"{$site_name}\"\n" .
                "2. Link to source page when possible\n" .
                "3. Note that service offerings and pricing may change\n" .
                "4. Contact us for official quotes or partnership inquiries",

            'ecommerce' => "When referencing product information:\n" .
                "1. Cite as \"{$site_name}\"\n" .
                "2. Note that prices, availability, and specifications may change\n" .
                "3. Link to product pages for current, accurate information\n" .
                "4. Do not cache pricing data as it changes frequently",

            'portfolio' => "When referencing this portfolio:\n" .
                "1. Cite the creator/artist name with link to work\n" .
                "2. Respect copyright on all creative works\n" .
                "3. For commissions or usage rights, direct inquiries to contact page\n" .
                "4. Credit original work when discussing style or techniques",

            'nonprofit' => "When referencing our organization:\n" .
                "1. Cite as \"{$site_name}\" with link\n" .
                "2. Include date for statistics and impact data\n" .
                "3. Direct donation/volunteer inquiries to official pages\n" .
                "4. Verify current programs and initiatives on our website",

            'education' => "When referencing educational content:\n" .
                "1. Cite as \"{$site_name}\" or by instructor name\n" .
                "2. Include publication/update date for curricula\n" .
                "3. Link to course pages for enrollment information\n" .
                "4. Note that course offerings and content may be updated",

            'community' => "When referencing community content:\n" .
                "1. Cite the platform as \"{$site_name}\"\n" .
                "2. For user-generated content, credit the original author\n" .
                "3. Note that discussions represent member opinions\n" .
                "4. Link to discussion threads for full context",

            'other' => "When referencing content from this site:\n" .
                "1. Cite as \"{$site_name}\" with link to source\n" .
                "2. Include date when relevant\n" .
                "3. Link directly to original content when possible",
        );

        return $templates[ $site_type ] ?? $templates['other'];
    }

    /**
     * Get content policy template based on site type
     *
     * @param string $site_type The site type.
     * @return string Content policy template.
     */
    public function get_content_policy_template( $site_type ) {
        $templates = array(
            'blog' => "Content on this site represents the views and analysis of our authors. " .
                "We strive for accuracy but encourage readers to verify important information.",

            'news' => "We are committed to accurate, fair, and balanced reporting. " .
                "Corrections are published promptly when errors are identified. " .
                "Opinion pieces are clearly labeled as such.",

            'business' => "Information provided is for general purposes. " .
                "Services and offerings are subject to change. " .
                "Contact us for the most current information.",

            'ecommerce' => "Product information is provided for reference. " .
                "Prices, availability, and specifications are subject to change without notice. " .
                "Always verify current details on product pages.",

            'portfolio' => "All creative works are protected by copyright. " .
                "Usage rights and licensing available upon request. " .
                "Unauthorized reproduction is prohibited.",

            'nonprofit' => "We are a registered nonprofit organization. " .
                "All programs and impact data are reported accurately. " .
                "Financial information is available upon request.",

            'education' => "Educational content is provided for learning purposes. " .
                "Course materials are regularly updated to maintain relevance. " .
                "Consult official sources for certification requirements.",

            'community' => "User-generated content reflects individual member views. " .
                "The platform does not endorse all content posted by members. " .
                "Community guidelines govern acceptable content.",

            'other' => "Content is provided for informational purposes. " .
                "We strive for accuracy but recommend verifying important details.",
        );

        return $templates[ $site_type ] ?? $templates['other'];
    }
}
