<?php
/**
 * Health checks for GetCited
 *
 * @package GetCited
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Health Check class
 */
class GetCited_Health_Check {

    /**
     * Single instance
     */
    private static $instance = null;

    /**
     * Transient name for cached status
     */
    const TRANSIENT_NAME = 'getcited_health_status';

    /**
     * Get instance
     */
    public static function instance() {
        if ( is_null( self::$instance ) ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Constructor
     */
    private function __construct() {
        // AJAX handler for manual health check
        add_action( 'wp_ajax_getcited_health_check', array( $this, 'ajax_run_checks' ) );
    }

    /**
     * Run all health checks
     */
    public function run_checks() {
        $status = array(
            'llms_txt' => $this->check_llms_txt(),
            'robots_txt' => $this->check_robots_txt(),
            'schema' => $this->check_schema(),
            'rewrite_rules' => $this->check_rewrite_rules(),
            'crawler_list' => $this->check_crawler_list(),
            'last_checked' => current_time( 'c' ),
        );

        // Calculate overall status
        $status['overall'] = $this->calculate_overall( $status );

        // Cache result
        set_transient( self::TRANSIENT_NAME, $status, HOUR_IN_SECONDS );

        // Fire hook
        do_action( 'getcited_health_check_complete', $status );

        return $status;
    }

    /**
     * Get cached status or run checks
     */
    public function get_status() {
        $status = get_transient( self::TRANSIENT_NAME );

        if ( $status === false ) {
            $status = $this->run_checks();
        }

        return $status;
    }

    /**
     * Force refresh status
     */
    public function refresh() {
        delete_transient( self::TRANSIENT_NAME );
        return $this->run_checks();
    }

    /**
     * AJAX handler for health check
     */
    public function ajax_run_checks() {
        check_ajax_referer( 'getcited_admin', 'nonce' );

        if ( ! current_user_can( 'manage_options' ) ) {
            wp_send_json_error( 'Permission denied' );
        }

        $status = $this->refresh();
        wp_send_json_success( $status );
    }

    /**
     * Check llms.txt accessibility
     */
    private function check_llms_txt() {
        $settings = GetCited_Settings::instance();
        
        if ( ! $settings->get( 'llms_txt_enabled' ) ) {
            return array(
                'status' => 'disabled',
                'message' => __( 'llms.txt is disabled', 'getcited' ),
            );
        }

        $url = home_url( '/llms.txt' );
        
        $response = wp_remote_get( $url, array(
            'timeout' => 5,
            'sslverify' => false,
        ) );

        if ( is_wp_error( $response ) ) {
            return array(
                'status' => 'error',
                'message' => $response->get_error_message(),
                'url' => $url,
            );
        }

        $code = wp_remote_retrieve_response_code( $response );
        $body = wp_remote_retrieve_body( $response );

        if ( $code !== 200 ) {
            return array(
                'status' => 'error',
                /* translators: %d: HTTP response code */
                'message' => sprintf( __( 'HTTP %d response', 'getcited' ), $code ),
                'url' => $url,
            );
        }

        // Check for our marker
        if ( strpos( $body, '# Generated by GetCited' ) === false ) {
            return array(
                'status' => 'warning',
                'message' => __( 'llms.txt accessible but may be served by another plugin', 'getcited' ),
                'url' => $url,
            );
        }

        return array(
            'status' => 'ok',
            'message' => __( 'llms.txt is accessible and working', 'getcited' ),
            'url' => $url,
        );
    }

    /**
     * Check robots.txt for our rules
     */
    private function check_robots_txt() {
        $url = home_url( '/robots.txt' );
        
        $response = wp_remote_get( $url, array(
            'timeout' => 5,
            'sslverify' => false,
        ) );

        if ( is_wp_error( $response ) ) {
            return array(
                'status' => 'error',
                'message' => $response->get_error_message(),
            );
        }

        $code = wp_remote_retrieve_response_code( $response );
        $body = wp_remote_retrieve_body( $response );

        if ( $code !== 200 ) {
            return array(
                'status' => 'error',
                /* translators: %d: HTTP response code */
                'message' => sprintf( __( 'HTTP %d response', 'getcited' ), $code ),
            );
        }

        // Check for our marker
        if ( strpos( $body, '# === GetCited AI Crawler Rules ===' ) === false ) {
            // Check if physical file exists
            $robots = GetCited_Robots::instance();
            if ( $robots->physical_file_exists() ) {
                return array(
                    'status' => 'warning',
                    'message' => __( 'A physical robots.txt file exists. GetCited rules may not be included.', 'getcited' ),
                );
            }

            return array(
                'status' => 'warning',
                'message' => __( 'GetCited rules not found in robots.txt', 'getcited' ),
            );
        }

        return array(
            'status' => 'ok',
            'message' => __( 'robots.txt includes GetCited rules', 'getcited' ),
        );
    }

    /**
     * Check schema output
     */
    private function check_schema() {
        $settings = GetCited_Settings::instance();
        
        if ( ! $settings->get( 'schema_enabled' ) ) {
            return array(
                'status' => 'disabled',
                'message' => __( 'Schema output is disabled', 'getcited' ),
            );
        }

        // Check for conflicts
        $schema = GetCited_Schema::instance();
        $conflicts = $schema->get_detected_plugins();

        if ( ! empty( $conflicts ) ) {
            $names = array_map( function( $p ) { return $p['name']; }, $conflicts );
            return array(
                'status' => 'warning',
                'message' => sprintf(
                    /* translators: %s: comma-separated list of detected schema plugin names */
                    __( 'Schema plugins detected: %s. This may cause duplicate schema.', 'getcited' ),
                    implode( ', ', $names )
                ),
                'conflicts' => $conflicts,
            );
        }

        $schema_types = $settings->get( 'schema_types' );
        $enabled = array_filter( $schema_types );

        if ( empty( $enabled ) ) {
            return array(
                'status' => 'warning',
                'message' => __( 'Schema is enabled but no schema types are selected', 'getcited' ),
            );
        }

        return array(
            'status' => 'ok',
            'message' => sprintf(
                /* translators: %s: comma-separated list of enabled schema types */
                __( 'Schema enabled for: %s', 'getcited' ),
                implode( ', ', array_keys( $enabled ) )
            ),
        );
    }

    /**
     * Check rewrite rules are flushed
     */
    private function check_rewrite_rules() {
        global $wp_rewrite;

        $rules = $wp_rewrite->wp_rewrite_rules();

        if ( ! isset( $rules['^llms\.txt$'] ) ) {
            return array(
                'status' => 'warning',
                'message' => __( 'Rewrite rules may need flushing. Visit Settings > Permalinks to refresh.', 'getcited' ),
            );
        }

        return array(
            'status' => 'ok',
            'message' => __( 'Rewrite rules are properly configured', 'getcited' ),
        );
    }

    /**
     * Check crawler list freshness
     */
    private function check_crawler_list() {
        $crawler_list = GetCited_Crawler_List::instance();
        
        $is_remote = $crawler_list->is_remote_cached();
        $version = $crawler_list->get_version();
        $updated = $crawler_list->get_last_updated();

        if ( ! $is_remote ) {
            return array(
                'status' => 'warning',
                'message' => __( 'Using bundled crawler list. Remote sync may have failed.', 'getcited' ),
                'version' => $version,
                'updated' => $updated,
            );
        }

        return array(
            'status' => 'ok',
            'message' => sprintf(
                /* translators: %1$s: version number, %2$s: last updated date */
                __( 'Crawler list v%1$s (updated %2$s)', 'getcited' ),
                $version,
                $updated
            ),
            'version' => $version,
            'updated' => $updated,
        );
    }

    /**
     * Calculate overall status
     */
    private function calculate_overall( $status ) {
        $checks = array( 'llms_txt', 'robots_txt', 'schema', 'rewrite_rules', 'crawler_list' );
        
        $has_error = false;
        $has_warning = false;

        foreach ( $checks as $check ) {
            if ( isset( $status[ $check ]['status'] ) ) {
                if ( $status[ $check ]['status'] === 'error' ) {
                    $has_error = true;
                } elseif ( $status[ $check ]['status'] === 'warning' ) {
                    $has_warning = true;
                }
            }
        }

        if ( $has_error ) {
            return 'error';
        }

        if ( $has_warning ) {
            return 'warning';
        }

        return 'ok';
    }

    /**
     * Get status label
     */
    public function get_status_label( $status ) {
        $labels = array(
            'ok' => __( 'Healthy', 'getcited' ),
            'warning' => __( 'Needs Attention', 'getcited' ),
            'error' => __( 'Error', 'getcited' ),
            'disabled' => __( 'Disabled', 'getcited' ),
        );

        return $labels[ $status ] ?? $status;
    }

    /**
     * Get status color class
     */
    public function get_status_class( $status ) {
        $classes = array(
            'ok' => 'getcited-status-ok',
            'warning' => 'getcited-status-warning',
            'error' => 'getcited-status-error',
            'disabled' => 'getcited-status-disabled',
        );

        return $classes[ $status ] ?? '';
    }
}
