<?php
/**
 * llms.txt generator for GetCited
 *
 * @package GetCited
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * llms.txt class
 */
class GetCited_Llms_Txt {

    /**
     * Single instance
     */
    private static $instance = null;

    /**
     * Get instance
     */
    public static function instance() {
        if ( is_null( self::$instance ) ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Constructor
     */
    private function __construct() {
        // Handle llms.txt requests
        add_action( 'template_redirect', array( $this, 'serve_llms_txt' ) );

        // Fallback via query var
        add_action( 'parse_request', array( $this, 'handle_query_var' ) );

        // Add link tag to head
        add_action( 'wp_head', array( $this, 'add_link_tag' ), 1 );
    }

    /**
     * Serve llms.txt via rewrite rule
     */
    public function serve_llms_txt() {
        global $wp_query;

        if ( ! isset( $wp_query->query_vars['getcited_llms_txt'] ) ) {
            return;
        }

        $this->output_llms_txt();
    }

    /**
     * Handle fallback query var (?llms-txt=1)
     */
    public function handle_query_var( $wp ) {
        // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Public endpoint like robots.txt, no nonce needed
        if ( isset( $_GET['llms-txt'] ) && sanitize_text_field( wp_unslash( $_GET['llms-txt'] ) ) === '1' ) {
            $this->output_llms_txt();
        }
    }

    /**
     * Output llms.txt content
     */
    private function output_llms_txt() {
        $settings = GetCited_Settings::instance();
        
        if ( ! $settings->get( 'llms_txt_enabled' ) ) {
            // Return 404 if disabled
            global $wp_query;
            $wp_query->set_404();
            status_header( 404 );
            return;
        }

        $content = $this->get_content();
        $content = apply_filters( 'getcited_llms_txt_content', $content );

        // Fire hook for tracking/logging
        do_action( 'getcited_llms_txt_served', $content );

        // Set headers
        status_header( 200 );
        header( 'Content-Type: text/plain; charset=utf-8' );
        header( 'X-Robots-Tag: noindex' );
        header( 'Cache-Control: public, max-age=86400' ); // Cache for 24 hours

        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Plain text file output, not HTML context
        echo $content;
        exit;
    }

    /**
     * Get llms.txt content
     */
    public function get_content() {
        $settings = GetCited_Settings::instance();
        $content = $settings->get( 'llms_txt_content' );

        // Ensure marker comment exists
        if ( strpos( $content, '# Generated by GetCited' ) === false ) {
            $content .= "\n\n---\n# Generated by GetCited";
        }

        return $content;
    }

    /**
     * Add link tag to site head
     */
    public function add_link_tag() {
        $settings = GetCited_Settings::instance();
        
        if ( ! $settings->get( 'llms_txt_enabled' ) ) {
            return;
        }

        $url = home_url( '/llms.txt' );
        echo '<link rel="llms-txt" href="' . esc_url( $url ) . '" />' . "\n";
    }

    /**
     * Generate template based on site type
     */
    public function generate_template( $site_type = 'blog' ) {
        $site_name = get_bloginfo( 'name' );
        $site_desc = get_bloginfo( 'description' );
        $site_url = home_url();
        $admin_email = get_option( 'admin_email' );

        $templates = array(
            'blog' => $this->get_blog_template( $site_name, $site_desc, $site_url ),
            'business' => $this->get_business_template( $site_name, $site_desc, $site_url ),
            'news' => $this->get_news_template( $site_name, $site_desc, $site_url ),
            'ecommerce' => $this->get_ecommerce_template( $site_name, $site_desc, $site_url ),
            'other' => $this->get_generic_template( $site_name, $site_desc, $site_url ),
        );

        return $templates[ $site_type ] ?? $templates['blog'];
    }

    /**
     * Blog template
     */
    private function get_blog_template( $name, $desc, $url ) {
        $recent_posts = $this->get_recent_posts( 5 );
        $categories = $this->get_categories();

        $content = "# {$name}\n\n";
        
        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "A blog sharing insights and knowledge.\n\n";
        $content .= "## About This Site\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Type: Blog\n";
        $content .= "- Content: Articles, guides, and commentary\n\n";

        if ( ! empty( $categories ) ) {
            $content .= "## Topics We Cover\n\n";
            foreach ( $categories as $cat ) {
                $content .= "- [{$cat['name']}]({$cat['url']}): {$cat['description']}\n";
            }
            $content .= "\n";
        }

        if ( ! empty( $recent_posts ) ) {
            $content .= "## Recent Articles\n\n";
            foreach ( $recent_posts as $post ) {
                $content .= "- [{$post['title']}]({$post['url']})\n";
            }
            $content .= "\n";
        }

        $content .= "## Key Pages\n\n";
        $content .= "- [Home]({$url}): Main page\n";
        $content .= "- [About]({$url}/about): About us\n";
        $content .= "- [Contact]({$url}/contact): Get in touch\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Business template
     */
    private function get_business_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";
        
        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## About Our Business\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Type: Business\n\n";

        $content .= "## Our Services\n\n";
        $content .= "- [Services]({$url}/services): What we offer\n";
        $content .= "- [About]({$url}/about): Our story\n";
        $content .= "- [Contact]({$url}/contact): Get in touch\n\n";

        $content .= "## Why Choose Us\n\n";
        $content .= "[Add your unique value proposition here]\n\n";

        $content .= "## Location & Contact\n\n";
        $content .= "- Address: [Your address]\n";
        $content .= "- Phone: [Your phone]\n";
        $content .= "- Email: [Your email]\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * News template
     */
    private function get_news_template( $name, $desc, $url ) {
        $recent_posts = $this->get_recent_posts( 10 );
        $categories = $this->get_categories();

        $content = "# {$name}\n\n";
        
        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "A news publication covering current events and analysis.\n\n";

        $content .= "## About This Publication\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Type: News/Media\n";
        $content .= "- Content: News articles, analysis, opinion\n\n";

        if ( ! empty( $categories ) ) {
            $content .= "## Sections\n\n";
            foreach ( $categories as $cat ) {
                $content .= "- [{$cat['name']}]({$cat['url']})\n";
            }
            $content .= "\n";
        }

        if ( ! empty( $recent_posts ) ) {
            $content .= "## Latest Articles\n\n";
            foreach ( $recent_posts as $post ) {
                $content .= "- [{$post['title']}]({$post['url']})\n";
            }
            $content .= "\n";
        }

        $content .= "## Editorial Policy\n\n";
        $content .= "We are committed to accurate, fair, and balanced reporting.\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * E-commerce template
     */
    private function get_ecommerce_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";
        
        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## About Our Store\n\n";
        $content .= "- Website: {$url}\n";
        $content .= "- Type: E-commerce\n\n";

        $content .= "## Product Categories\n\n";
        $content .= "- [Shop]({$url}/shop): Browse all products\n";
        $content .= "[Add your main product categories here]\n\n";

        $content .= "## Customer Information\n\n";
        $content .= "- [Shipping]({$url}/shipping): Shipping policy\n";
        $content .= "- [Returns]({$url}/returns): Return policy\n";
        $content .= "- [FAQ]({$url}/faq): Frequently asked questions\n";
        $content .= "- [Contact]({$url}/contact): Customer support\n\n";

        $content .= "## About Us\n\n";
        $content .= "[Add your company story here]\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Generic template
     */
    private function get_generic_template( $name, $desc, $url ) {
        $content = "# {$name}\n\n";
        
        if ( ! empty( $desc ) ) {
            $content .= "> {$desc}\n\n";
        }

        $content .= "## About\n\n";
        $content .= "- Website: {$url}\n\n";

        $content .= "## Main Sections\n\n";
        $content .= "- [Home]({$url})\n";
        $content .= "- [About]({$url}/about)\n";
        $content .= "- [Contact]({$url}/contact)\n\n";

        $content .= "---\n";
        $content .= "# Generated by GetCited";

        return $content;
    }

    /**
     * Get recent posts for template
     */
    private function get_recent_posts( $count = 5 ) {
        $posts = get_posts( array(
            'numberposts' => $count,
            'post_status' => 'publish',
        ) );

        $result = array();
        foreach ( $posts as $post ) {
            $result[] = array(
                'title' => $post->post_title,
                'url' => get_permalink( $post->ID ),
            );
        }

        return $result;
    }

    /**
     * Get categories for template
     */
    private function get_categories() {
        $cats = get_categories( array(
            'orderby' => 'count',
            'order' => 'DESC',
            'number' => 10,
            'hide_empty' => true,
        ) );

        $result = array();
        foreach ( $cats as $cat ) {
            $result[] = array(
                'name' => $cat->name,
                'url' => get_category_link( $cat->term_id ),
                'description' => $cat->description ?: "Articles about {$cat->name}",
            );
        }

        return $result;
    }

    /**
     * Validate llms.txt content format
     */
    public function validate( $content ) {
        $warnings = array();
        $errors = array();

        // Check for required elements
        if ( strpos( $content, '#' ) === false ) {
            $warnings[] = __( 'No headings found. Consider adding a title with #', 'getcited' );
        }

        // Check for empty content
        if ( strlen( trim( $content ) ) < 50 ) {
            $warnings[] = __( 'Content seems too short. Add more information about your site.', 'getcited' );
        }

        // Check for broken links syntax
        if ( preg_match( '/\[([^\]]*)\]\([^)]*\s[^)]*\)/', $content ) ) {
            $errors[] = __( 'Malformed markdown links detected. Links should be [text](url)', 'getcited' );
        }

        return array(
            'valid' => empty( $errors ),
            'errors' => $errors,
            'warnings' => $warnings,
        );
    }

    /**
     * Get llms.txt URL
     */
    public function get_url() {
        return home_url( '/llms.txt' );
    }

    /**
     * Get fallback URL
     */
    public function get_fallback_url() {
        return home_url( '/?llms-txt=1' );
    }
}
