<?php
/**
 * Health checks for GetCited
 *
 * @package GetCited
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Health Check class
 */
class GetCited_Health_Check {

    /**
     * Single instance
     */
    private static $instance = null;

    /**
     * Transient name for cached status
     */
    const TRANSIENT_NAME = 'getcited_health_status';

    /**
     * Get instance
     */
    public static function instance() {
        if ( is_null( self::$instance ) ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Constructor
     */
    private function __construct() {
        // AJAX handler for manual health check
        add_action( 'wp_ajax_getcited_health_check', array( $this, 'ajax_run_checks' ) );
    }

    /**
     * Invalidate the health check cache
     *
     * Called by other classes when they make changes that affect health status.
     */
    public function invalidate_cache() {
        delete_transient( self::TRANSIENT_NAME );
    }

    /**
     * Run all health checks
     */
    public function run_checks() {
        $status = array(
            'llms_txt' => $this->check_llms_txt(),
            'robots_txt' => $this->check_robots_txt(),
            'schema' => $this->check_schema(),
            'rewrite_rules' => $this->check_rewrite_rules(),
            'crawler_list' => $this->check_crawler_list(),
            'last_checked' => current_time( 'c' ),
        );

        // Calculate overall status
        $status['overall'] = $this->calculate_overall( $status );

        // Cache result
        set_transient( self::TRANSIENT_NAME, $status, HOUR_IN_SECONDS );

        // Fire hook
        do_action( 'getcited_health_check_complete', $status );

        return $status;
    }

    /**
     * Get cached status or run checks
     */
    public function get_status() {
        $status = get_transient( self::TRANSIENT_NAME );

        if ( $status === false ) {
            $status = $this->run_checks();
        }

        return $status;
    }

    /**
     * Force refresh status
     */
    public function refresh() {
        delete_transient( self::TRANSIENT_NAME );
        return $this->run_checks();
    }

    /**
     * AJAX handler for health check
     */
    public function ajax_run_checks() {
        check_ajax_referer( 'getcited_admin', 'nonce' );

        if ( ! current_user_can( 'manage_options' ) ) {
            wp_send_json_error( 'Permission denied' );
        }

        $status = $this->refresh();
        wp_send_json_success( $status );
    }

    /**
     * Check llms.txt accessibility
     */
    private function check_llms_txt() {
        $settings = GetCited_Settings::instance();
        $detector = GetCited_Conflict_Detector::instance();
        $summary = $detector->get_llms_txt_summary();

        if ( ! $settings->get( 'llms_txt_enabled' ) ) {
            return array(
                'status' => 'disabled',
                'message' => __( 'llms.txt is disabled', 'getcited' ),
                'action_type' => 'settings_link',
                'action_url' => admin_url( 'admin.php?page=getcited-llms-txt' ),
                'action_label' => __( 'Enable llms.txt', 'getcited' ),
            );
        }

        // Check for physical llms.txt file first
        if ( $summary['physical_file_exists'] ) {
            $file_path = ABSPATH . 'llms.txt';

            // Use WP_Filesystem for consistent file operations
            global $wp_filesystem;
            if ( ! function_exists( 'WP_Filesystem' ) ) {
                require_once ABSPATH . 'wp-admin/includes/file.php';
            }
            WP_Filesystem();

            $content = $wp_filesystem->get_contents( $file_path );

            // Check if it's ours
            if ( $content && strpos( $content, '# Generated by GetCited' ) !== false ) {
                return array(
                    'status' => 'ok',
                    'message' => __( 'llms.txt physical file present (GetCited)', 'getcited' ),
                    'url' => home_url( '/llms.txt' ),
                );
            }

            // Physical file exists but not ours
            $source = $content ? $this->identify_llms_txt_source( $content ) : false;

            return array(
                'status' => 'warning',
                'message' => __( 'Physical llms.txt file exists', 'getcited' ),
                'details' => $source
                    ? sprintf(
                        /* translators: %s: identified source */
                        __( 'A physical llms.txt file exists, possibly created by %s. This takes precedence over GetCited. Delete the physical file to use GetCited, or edit it directly.', 'getcited' ),
                        $source
                    )
                    : __( 'A physical llms.txt file in your site root takes precedence over GetCited. Delete the physical file to use GetCited, or edit it to include your desired content.', 'getcited' ),
                'file_path' => $file_path,
                'action_type' => 'copy_content',
                'content' => $settings->get( 'llms_txt_content' ),
                'current_content_preview' => $content ? substr( $content, 0, 500 ) : '',
            );
        }

        // Check for other handlers
        if ( ! empty( $summary['other_handlers'] ) ) {
            // Another plugin is handling llms.txt
            $other_plugin = null;
            foreach ( $summary['other_handlers'] as $handler ) {
                if ( ! empty( $handler['plugin'] ) ) {
                    $other_plugin = $detector->get_plugin_info( $handler['plugin'] );
                    break;
                }
            }

            // Still fetch to see what's actually served
            $url = home_url( '/llms.txt' );
            $response = wp_remote_get( $url, array( 'timeout' => 5 ) );

            if ( ! is_wp_error( $response ) && wp_remote_retrieve_response_code( $response ) === 200 ) {
                $body = wp_remote_retrieve_body( $response );

                // Check if GetCited marker is present
                if ( strpos( $body, '# Generated by GetCited' ) !== false ) {
                    return array(
                        'status' => 'ok',
                        'message' => __( 'llms.txt is accessible and working', 'getcited' ),
                        'details' => $other_plugin
                            ? sprintf(
                                /* translators: %s: plugin name */
                                __( 'Note: %s also has llms.txt handling registered, but GetCited is currently serving the file.', 'getcited' ),
                                $other_plugin['name']
                            )
                            : null,
                        'url' => $url,
                    );
                }

                // Another plugin is serving llms.txt
                return array(
                    'status' => 'warning',
                    'message' => __( 'llms.txt served by another plugin', 'getcited' ),
                    'details' => $other_plugin
                        ? sprintf(
                            /* translators: %s: plugin name */
                            __( '%s is currently serving llms.txt. Disable their llms.txt feature to use GetCited, or configure your content through their interface.', 'getcited' ),
                            $other_plugin['name']
                        )
                        : __( 'Another plugin is serving llms.txt. You may need to disable their llms.txt feature to use GetCited.', 'getcited' ),
                    'url' => $url,
                    'content_preview' => substr( $body, 0, 500 ),
                    'other_plugin' => $other_plugin,
                );
            }
        }

        // Standard fetch check
        $url = home_url( '/llms.txt' );

        $response = wp_remote_get( $url, array( 'timeout' => 5 ) );

        if ( is_wp_error( $response ) ) {
            return array(
                'status' => 'error',
                'message' => __( 'Could not fetch llms.txt', 'getcited' ),
                'details' => $response->get_error_message(),
                'url' => $url,
            );
        }

        $code = wp_remote_retrieve_response_code( $response );
        $body = wp_remote_retrieve_body( $response );

        if ( $code === 404 ) {
            return array(
                'status' => 'error',
                'message' => __( 'llms.txt returns 404 Not Found', 'getcited' ),
                'details' => __( 'The rewrite rules may need flushing. Go to Settings → Permalinks and click Save Changes.', 'getcited' ),
                'action_type' => 'permalinks_link',
                'action_url' => admin_url( 'options-permalink.php' ),
                'action_label' => __( 'Go to Permalinks', 'getcited' ),
                'url' => $url,
            );
        }

        if ( $code !== 200 ) {
            return array(
                'status' => 'error',
                /* translators: %d: HTTP response code */
                'message' => sprintf( __( 'llms.txt returned HTTP %d', 'getcited' ), $code ),
                'url' => $url,
            );
        }

        // Check for our marker
        if ( strpos( $body, '# Generated by GetCited' ) === false ) {
            $source = $this->identify_llms_txt_source( $body );

            return array(
                'status' => 'warning',
                'message' => __( 'llms.txt served by another source', 'getcited' ),
                'details' => $source
                    ? sprintf(
                        /* translators: %s: name of conflicting source */
                        __( '%s appears to be serving llms.txt. Disable their llms.txt feature or use theirs instead.', 'getcited' ),
                        $source
                    )
                    : __( 'The llms.txt file is accessible but not generated by GetCited. Another plugin or a physical file may be serving it.', 'getcited' ),
                'url' => $url,
                'content_preview' => substr( $body, 0, 500 ),
            );
        }

        return array(
            'status' => 'ok',
            'message' => __( 'llms.txt is accessible and working', 'getcited' ),
            'url' => $url,
        );
    }

    /**
     * Try to identify the source of llms.txt content
     *
     * @param string $content The llms.txt content
     * @return string|false Source name or false if unknown
     */
    private function identify_llms_txt_source( $content ) {
        // Check for known signatures
        $signatures = array(
            'Yoast SEO' => array( 'yoast', 'Yoast' ),
            'Rank Math' => array( 'rank-math', 'Rank Math', 'rankmath' ),
            'All in One SEO' => array( 'aioseo', 'All in One SEO', 'AIOSEO' ),
            'SEOPress' => array( 'seopress', 'SEOPress' ),
            'JERL' => array( 'jerl', 'JERL' ),
            'LLMs.txt Plugin' => array( 'llms-txt', 'LLMs.txt' ),
            'WP LLMs' => array( 'wp-llms', 'WP LLMs' ),
        );

        foreach ( $signatures as $name => $keywords ) {
            foreach ( $keywords as $keyword ) {
                if ( stripos( $content, $keyword ) !== false ) {
                    return $name;
                }
            }
        }

        // Check if it looks like a manual/physical file
        if ( strpos( $content, '# Generated' ) === false ) {
            return __( 'Physical file or unknown source', 'getcited' );
        }

        return false;
    }

    /**
     * Check robots.txt for our rules
     */
    private function check_robots_txt() {
        $robots = GetCited_Robots::instance();
        $detector = GetCited_Conflict_Detector::instance();
        $summary = $detector->get_robots_txt_summary();

        // Check if site discourages search engines
        $is_public = get_option( 'blog_public' );
        if ( ! $is_public ) {
            return array(
                'status' => 'error',
                'message' => __( 'Site is set to discourage search engines', 'getcited' ),
                'details' => __( 'WordPress is blocking all crawlers. Go to Settings → Reading and uncheck "Discourage search engines from indexing this site" to allow AI crawlers.', 'getcited' ),
                'action_type' => 'settings_link',
                'action_url' => admin_url( 'options-reading.php' ),
                'action_label' => __( 'Go to Reading Settings', 'getcited' ),
            );
        }

        // Check for physical robots.txt file
        if ( $summary['physical_file_exists'] ) {
            $rules_exist = $robots->rules_exist_in_physical_file();

            // Rules already present
            if ( $rules_exist ) {
                $result = array(
                    'status' => 'ok',
                    'message' => __( 'GetCited rules present in robots.txt', 'getcited' ),
                );

                // Note if SEO plugin editor is available
                if ( $summary['seo_plugin_with_editor'] ) {
                    $result['details'] = sprintf(
                        /* translators: %s: SEO plugin name */
                        __( 'Physical file managed alongside %s. Edit via GetCited Crawlers page or the SEO plugin editor.', 'getcited' ),
                        $summary['seo_plugin_with_editor']['name']
                    );
                }

                return $result;
            }

            // Physical file exists, rules not present
            $result = array(
                'status' => 'warning',
                'message' => __( 'Physical robots.txt exists — GetCited rules not added yet', 'getcited' ),
                'rules' => $robots->generate_rules(),
                'can_write' => $summary['physical_file_writable'],
            );

            // Build details message
            if ( $summary['seo_plugin_with_editor'] ) {
                $result['details'] = sprintf(
                    /* translators: %s: SEO plugin name */
                    __( 'A robots.txt file exists, likely managed by %s. You can add GetCited rules automatically, or add them through your SEO plugin editor.', 'getcited' ),
                    $summary['seo_plugin_with_editor']['name']
                );
                $result['seo_plugin'] = $summary['seo_plugin_with_editor'];
            } elseif ( ! empty( $summary['hooks_detected'] ) ) {
                // Other plugins detected but no known editor
                $plugin_names = array();
                foreach ( $summary['hooks_detected'] as $hook ) {
                    if ( $hook['plugin_info'] ) {
                        $plugin_names[] = $hook['plugin_info']['name'];
                    } elseif ( $hook['plugin'] ) {
                        $plugin_names[] = ucfirst( $hook['plugin'] );
                    }
                }
                $plugin_names = array_unique( $plugin_names );

                if ( ! empty( $plugin_names ) ) {
                    $result['details'] = sprintf(
                        /* translators: %s: comma-separated list of plugin names */
                        __( 'A robots.txt file exists. Detected plugins that may modify it: %s. You can add GetCited rules automatically.', 'getcited' ),
                        implode( ', ', $plugin_names )
                    );
                    $result['detected_plugins'] = $plugin_names;
                } else {
                    $result['details'] = __( 'A physical robots.txt file exists in your site root. GetCited can add its rules automatically.', 'getcited' );
                }
            } else {
                $result['details'] = __( 'A physical robots.txt file exists in your site root. GetCited can add its rules automatically.', 'getcited' );
            }

            // Set action type based on write capability
            if ( $summary['physical_file_writable'] ) {
                $result['action_type'] = 'auto_add';
                $result['action_label'] = __( 'Add Rules to robots.txt', 'getcited' );
            } else {
                $result['action_type'] = 'copy_rules';
                $result['details'] .= ' ' . __( 'Automatic addition is not available due to file permissions.', 'getcited' );
            }

            return $result;
        }

        // No physical file - using WordPress filter
        // Fetch and check robots.txt content
        $url = home_url( '/robots.txt' );

        $response = wp_remote_get( $url, array( 'timeout' => 5 ) );

        if ( is_wp_error( $response ) ) {
            return array(
                'status' => 'error',
                'message' => __( 'Could not fetch robots.txt', 'getcited' ),
                'details' => $response->get_error_message(),
            );
        }

        $code = wp_remote_retrieve_response_code( $response );
        $body = wp_remote_retrieve_body( $response );

        if ( $code !== 200 ) {
            return array(
                'status' => 'error',
                /* translators: %d: HTTP response code */
                'message' => sprintf( __( 'robots.txt returned HTTP %d', 'getcited' ), $code ),
                'details' => __( 'The robots.txt file could not be loaded. Check your server configuration.', 'getcited' ),
            );
        }

        // Check for our marker
        if ( strpos( $body, '# === GetCited AI Crawler Rules ===' ) === false ) {
            // Check if other hooks might be interfering
            if ( ! empty( $summary['potential_conflicts'] ) ) {
                $conflict_names = array_map( function ( $c ) {
                    return $c['plugin'];
                }, $summary['potential_conflicts'] );

                return array(
                    'status' => 'warning',
                    'message' => __( 'GetCited rules may be overwritten', 'getcited' ),
                    'details' => sprintf(
                        /* translators: %s: comma-separated list of plugin names */
                        __( 'The following plugins run after GetCited and may be removing or overwriting the rules: %s. Try adjusting plugin load order or contact support.', 'getcited' ),
                        implode( ', ', $conflict_names )
                    ),
                    'hooks_info' => $summary['hooks_detected'],
                );
            }

            return array(
                'status' => 'warning',
                'message' => __( 'GetCited rules not found in robots.txt', 'getcited' ),
                'details' => __( 'The rules should be added automatically. Try deactivating and reactivating GetCited, or flush your permalinks by visiting Settings → Permalinks and clicking Save.', 'getcited' ),
                'action_type' => 'permalinks_link',
                'action_url' => admin_url( 'options-permalink.php' ),
                'action_label' => __( 'Go to Permalinks', 'getcited' ),
                'rules' => $robots->generate_rules(),
            );
        }

        // All good - rules present
        $result = array(
            'status' => 'ok',
            'message' => __( 'robots.txt includes GetCited rules', 'getcited' ),
        );

        // Note other hooks if present
        if ( ! empty( $summary['hooks_detected'] ) ) {
            $plugin_names = array();
            foreach ( $summary['hooks_detected'] as $hook ) {
                if ( $hook['plugin_info'] ) {
                    $plugin_names[] = $hook['plugin_info']['name'];
                }
            }
            $plugin_names = array_unique( $plugin_names );

            if ( ! empty( $plugin_names ) ) {
                $result['details'] = sprintf(
                    /* translators: %s: comma-separated list of plugin names */
                    __( 'Also detected: %s. All plugins are cooperating correctly.', 'getcited' ),
                    implode( ', ', $plugin_names )
                );
            }
        }

        return $result;
    }

    /**
     * Check schema output
     */
    private function check_schema() {
        $settings = GetCited_Settings::instance();
        
        if ( ! $settings->get( 'schema_enabled' ) ) {
            return array(
                'status' => 'disabled',
                'message' => __( 'Schema output is disabled', 'getcited' ),
            );
        }

        // Check for conflicts
        $schema = GetCited_Schema::instance();
        $conflicts = $schema->get_detected_plugins();

        if ( ! empty( $conflicts ) ) {
            $names = array_map( function( $p ) { return $p['name']; }, $conflicts );
            return array(
                'status' => 'warning',
                'message' => sprintf(
                    /* translators: %s: comma-separated list of detected schema plugin names */
                    __( 'Schema plugins detected: %s. This may cause duplicate schema.', 'getcited' ),
                    implode( ', ', $names )
                ),
                'conflicts' => $conflicts,
            );
        }

        $schema_types = $settings->get( 'schema_types' );
        $enabled = array_filter( $schema_types );

        if ( empty( $enabled ) ) {
            return array(
                'status' => 'warning',
                'message' => __( 'Schema is enabled but no schema types are selected', 'getcited' ),
            );
        }

        return array(
            'status' => 'ok',
            'message' => sprintf(
                /* translators: %s: comma-separated list of enabled schema types */
                __( 'Schema enabled for: %s', 'getcited' ),
                implode( ', ', array_keys( $enabled ) )
            ),
        );
    }

    /**
     * Check rewrite rules are flushed
     */
    private function check_rewrite_rules() {
        global $wp_rewrite;

        $rules = $wp_rewrite->wp_rewrite_rules();

        if ( ! isset( $rules['^llms\.txt$'] ) ) {
            return array(
                'status' => 'warning',
                'message' => __( 'Rewrite rules may need flushing. Visit Settings > Permalinks to refresh.', 'getcited' ),
            );
        }

        return array(
            'status' => 'ok',
            'message' => __( 'Rewrite rules are properly configured', 'getcited' ),
        );
    }

    /**
     * Check crawler list freshness
     */
    private function check_crawler_list() {
        $crawler_list = GetCited_Crawler_List::instance();

        $is_remote = $crawler_list->is_remote_cached();
        $version = $crawler_list->get_version();
        $updated = $crawler_list->get_last_updated();

        // If using bundled list, show OK status (bundled list is valid and usable)
        if ( ! $is_remote ) {
            return array(
                'status' => 'ok',
                'message' => sprintf(
                    /* translators: %s: version number */
                    __( 'Using bundled crawler list v%s', 'getcited' ),
                    $version
                ),
                'version' => $version,
                'updated' => $updated,
                'details' => __( 'Remote sync will be attempted automatically. The bundled list is fully functional.', 'getcited' ),
            );
        }

        return array(
            'status' => 'ok',
            'message' => sprintf(
                /* translators: %1$s: version number, %2$s: last updated date */
                __( 'Crawler list v%1$s (updated %2$s)', 'getcited' ),
                $version,
                $updated
            ),
            'version' => $version,
            'updated' => $updated,
        );
    }

    /**
     * Calculate overall status
     */
    private function calculate_overall( $status ) {
        $checks = array( 'llms_txt', 'robots_txt', 'schema', 'rewrite_rules', 'crawler_list' );
        
        $has_error = false;
        $has_warning = false;

        foreach ( $checks as $check ) {
            if ( isset( $status[ $check ]['status'] ) ) {
                if ( $status[ $check ]['status'] === 'error' ) {
                    $has_error = true;
                } elseif ( $status[ $check ]['status'] === 'warning' ) {
                    $has_warning = true;
                }
            }
        }

        if ( $has_error ) {
            return 'error';
        }

        if ( $has_warning ) {
            return 'warning';
        }

        return 'ok';
    }

    /**
     * Get status label
     */
    public function get_status_label( $status ) {
        $labels = array(
            'ok' => __( 'Healthy', 'getcited' ),
            'warning' => __( 'Needs Attention', 'getcited' ),
            'error' => __( 'Error', 'getcited' ),
            'disabled' => __( 'Disabled', 'getcited' ),
        );

        return $labels[ $status ] ?? $status;
    }

    /**
     * Get status color class
     */
    public function get_status_class( $status ) {
        $classes = array(
            'ok' => 'getcited-status-ok',
            'warning' => 'getcited-status-warning',
            'error' => 'getcited-status-error',
            'disabled' => 'getcited-status-disabled',
        );

        return $classes[ $status ] ?? '';
    }
}
